services:
  postgres:
    image: postgres:latest
    container_name: receitafederal-postgres
    restart: always
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: receitafederal_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_receitafederal_data:/var/lib/postgresql/data

networks:
  receitafederal-base-network:
    driver: bridge

volumes:
  postgres_receitafederal_data: